version: 3

experimental:
  gradle:
    # other configurations will be excluded, we don't wish to analyze compile only and test dependencies
    #
    # full list of gradle configurations created with the following command:
    # ./gradlew --console plain splunk-otel-android:dependencies | fgrep ' - ' | sed -e 's/ - .*//' | sed -e 's/^/- /'
    configurations-only:
#      - _internal-unified-test-platform-android-device-provider-ddmlib
#      - _internal-unified-test-platform-android-device-provider-gradle
#      - _internal-unified-test-platform-android-driver-instrumentation
#      - _internal-unified-test-platform-android-test-plugin
#      - _internal-unified-test-platform-android-test-plugin-host-additional-test-output
#      - _internal-unified-test-platform-android-test-plugin-host-apk-installer
#      - _internal-unified-test-platform-android-test-plugin-host-coverage
#      - _internal-unified-test-platform-android-test-plugin-host-device-info
#      - _internal-unified-test-platform-android-test-plugin-host-emulator-control
#      - _internal-unified-test-platform-android-test-plugin-host-logcat
#      - _internal-unified-test-platform-android-test-plugin-host-retention
#      - _internal-unified-test-platform-android-test-plugin-result-listener-gradle
#      - _internal-unified-test-platform-core
#      - _internal-unified-test-platform-launcher
      - androidApis
      - androidJdkImage
      - androidTestAnnotationProcessor
      - androidTestCompileOnly
      - androidTestDebugAnnotationProcessor
      - androidTestDebugCompileOnly
      - androidTestDebugImplementation
      - androidTestDebugRuntimeOnly
      - androidTestDebugWearApp
      - androidTestImplementation
      - androidTestReleaseAnnotationProcessor
      - androidTestReleaseCompileOnly
      - androidTestReleaseImplementation
      - androidTestReleaseRuntimeOnly
      - androidTestReleaseWearApp
      - androidTestRuntimeOnly
      - androidTestUtil
      - androidTestWearApp
      - annotationProcessor
      - api
      - compileOnly
      - compileOnlyApi
      - coreLibraryDesugaring
      - debugAndroidTestAnnotationProcessorClasspath
      - debugAndroidTestCompileClasspath
      - debugAndroidTestRuntimeClasspath
      - debugAnnotationProcessor
      - debugAnnotationProcessorClasspath
      - debugApi
      - debugApiElements
      - debugCompileClasspath
      - debugCompileOnly
      - debugCompileOnlyApi
      - debugImplementation
      - debugRuntimeClasspath
      - debugRuntimeElements
      - debugRuntimeOnly
      - debugUnitTestAnnotationProcessorClasspath
      - debugUnitTestCompileClasspath
      - debugUnitTestRuntimeClasspath
      - debugWearApp
      - errorprone
      - errorproneJavac
      - implementation
      - lintChecks
      - lintPublish
      - releaseAnnotationProcessor
      - releaseAnnotationProcessorClasspath
      - releaseApi
      - releaseApiElements
      - releaseCompileClasspath
      - releaseCompileOnly
      - releaseCompileOnlyApi
      - releaseImplementation
      - releaseRuntimeClasspath
      - releaseRuntimeElements
      - releaseRuntimeOnly
      - releaseUnitTestAnnotationProcessorClasspath
      - releaseUnitTestCompileClasspath
      - releaseUnitTestRuntimeClasspath
      - releaseVariantReleaseApiPublication
      - releaseVariantReleaseRuntimePublication
      - releaseWearApp
      - runtimeOnly
      - testAnnotationProcessor
      - testCompileOnly
      - testDebugAnnotationProcessor
      - testDebugCompileOnly
      - testDebugImplementation
      - testDebugRuntimeOnly
      - testDebugWearApp
      - testFixturesAnnotationProcessor
      - testFixturesApi
      - testFixturesCompileOnly
      - testFixturesCompileOnlyApi
      - testFixturesDebugAnnotationProcessor
      - testFixturesDebugApi
      - testFixturesDebugCompileOnly
      - testFixturesDebugCompileOnlyApi
      - testFixturesDebugImplementation
      - testFixturesDebugRuntimeOnly
      - testFixturesDebugWearApp
      - testFixturesImplementation
      - testFixturesReleaseAnnotationProcessor
      - testFixturesReleaseApi
      - testFixturesReleaseCompileOnly
      - testFixturesReleaseCompileOnlyApi
      - testFixturesReleaseImplementation
      - testFixturesReleaseRuntimeOnly
      - testFixturesReleaseWearApp
      - testFixturesRuntimeOnly
      - testFixturesWearApp
      - testImplementation
      - testReleaseAnnotationProcessor
      - testReleaseCompileOnly
      - testReleaseImplementation
      - testReleaseRuntimeOnly
      - testReleaseWearApp
      - testRuntimeOnly
      - testWearApp
      - wearApp
